/*
 * Portfolio Website JavaScript
 * Author: Anthony Lin
 *
 * AI Usage Documentation:
 * - Mobile navigation toggle logic generated by Claude AI
 * - Event listener structure and naming conventions from AI suggestion
 * - Added custom close-on-click-outside functionality after testing
 * - Smooth scroll behavior added based on AI recommendation
 * - Loading animation control added with AI assistance
 * - Aniimations were made by Copilot based on my description

 */

// Page Loading Animation
// Hides loader after page content is fully loaded
window.addEventListener("load", () => {
  const loader = document.querySelector(".loader-wrapper");
  if (loader) {
    // Small delay for smoother transition
    setTimeout(() => {
      loader.classList.add("hidden");
      // Remove from DOM after animation completes
      setTimeout(() => {
        loader.style.display = "none";
      }, 500);
    }, 500); // Shows loader for minimum 800ms
  }
});

// Mobile Navigation Toggle
document.addEventListener("DOMContentLoaded", () => {
  const navToggle = document.querySelector(".nav-toggle");
  const navMenu =
    document.getElementById("primary-navigation") ||
    document.querySelector(".nav-menu");

  // Check if elements exist before adding listeners (defensive programming)
  if (navToggle && navMenu) {
    // Toggle mobile menu when hamburger clicked
    navToggle.addEventListener("click", () => {
      const opened = navToggle.classList.toggle("active");
      navMenu.classList.toggle("active");
      // update accessible state
      navToggle.setAttribute("aria-expanded", opened ? "true" : "false");
    });

    // Close menu when clicking outside - improves UX
    // AI suggested this pattern, I tested and confirmed it works well
    document.addEventListener("click", (e) => {
      if (!navToggle.contains(e.target) && !navMenu.contains(e.target)) {
        navToggle.classList.remove("active");
        navMenu.classList.remove("active");
        navToggle.setAttribute("aria-expanded", "false");
      }
    });

    // Close menu when clicking a navigation link
    // Prevents menu staying open after navigation on mobile
    const navLinks = navMenu.querySelectorAll("a");
    navLinks.forEach((link) => {
      link.addEventListener("click", () => {
        navToggle.classList.remove("active");
        navMenu.classList.remove("active");
        navToggle.setAttribute("aria-expanded", "false");
      });
    });
  }

  // Smooth scroll for anchor links (optional enhancement)
  // Works for in-page navigation if we add sections later
  const anchorLinks = document.querySelectorAll('a[href^="#"]');
  anchorLinks.forEach((link) => {
    link.addEventListener("click", (e) => {
      const href = link.getAttribute("href");
      if (href !== "#") {
        const target = document.querySelector(href);
        if (target) {
          e.preventDefault();
          // Smooth scroll behavior - built into modern browsers
          target.scrollIntoView({
            behavior: "smooth",
            block: "start",
          });
        }
      }
    });
  });
});
